VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

QMK_SETTINGS = no
COMBO_ENABLE = no
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
